## "makeCacheMatrix" generates a list of operations from which to choose
## in the "cacheSolve" operation

## overal cachesolve(makeCacheMatrix(x)) [being x an invertable matrix] 
## returns the inverse matrix to A, looking it up in the cache if it was 
## calculated earlyer or calculating it otherwhise

makeCacheMatrix <- function(x = matrix()) {
            m <- NULL 
            set <- function(y) {
                  x <<- y
                  m <<- NULL
            }                   #assigns values outside the enviroment 
                                #of the function, changing the value and 
                                #deleting cache 
            get <- function() x 
            setinverse <- function(solve) m <<- solve #calculates inverse
            getinverse <- function() m         #assigns by default to null
            list(set = set, get = get          #generates the list of operations
                 setinverse = setinverse,
                 getinverse = getinverse)
}


## looks up is the inverse of a matrix (list) generated by the function above
## in the cache, if it is not present in the cache it calculates it and saves
## it in the cache
cacheSolve <- function(x, ...) {
      m <- x$getinverse()               #looks up the cache
      if(!is.null(m)) {                 
            message("getting cached data")
            return(m)                   #return value in cache(if present)
      }
      data <- x$get()
      m <- solve(data, ...)             #otherwise calculates the inverse
      x$setinverse(m)                   #and sets it as the cache of the matrix
      m
}
        ## Returns a matrix that is the inverse of 'x'

